# Generated by Django 2.2.13 on 2020-12-21 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='guideline',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.DeleteModel(
            name='DocumentAnnotation',
        ),
    ]
