# Generated by Django 2.2.13 on 2021-05-08 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='label',
            name='prefix_key',
        ),
    ]
