# Generated by Django 2.2.13 on 2021-05-30 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='entity_concordance',
        ),
        migrations.RemoveField(
            model_name='project',
            name='relation_concordance',
        ),
    ]
