# Generated by Django 2.2.13 on 2021-05-01 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210502_0617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seq_connections', to='api.Document'),
        ),
    ]
