# Generated by Django 2.2.13 on 2021-05-08 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210508_1527'),
    ]

    operations = [
        migrations.RenameField(
            model_name='relation',
            old_name='background_color',
            new_name='color',
        ),
    ]
