# Generated by Django 2.2.13 on 2021-05-08 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210508_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='relation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Relation'),
        ),
    ]
