# Generated by Django 2.2.13 on 2021-05-11 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210508_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='concordance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='connection',
            name='relation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Relation'),
        ),
    ]
