# Generated by Django 2.2.13 on 2021-05-11 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210511_2037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='concordance',
        ),
        migrations.AddField(
            model_name='document',
            name='entity_concordance',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=4),
        ),
    ]
