# Generated by Django 2.2.13 on 2021-05-11 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20210512_0120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='entity_concordance',
            field=models.DecimalField(decimal_places=4, default=1.0, max_digits=5),
        ),
    ]
