# Generated by Django 2.2.13 on 2021-05-12 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20210512_0124'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='relation_concordance',
            field=models.DecimalField(decimal_places=4, default=1.0, max_digits=6),
        ),
    ]
