version: "3.7"
services:

  backend:
    build: ./backend
    volumes:
      - ./backend:/backend
    command: ["/backend/django.sh"]
    environment:
      ADMIN_USERNAME: "admin"
      ADMIN_PASSWORD: "root"
      ADMIN_EMAIL: "admin@example.com"
    ports:
      - 8000:8000

  frontend:
    build: ./frontend
    command: ["/frontend/dev-nuxt.sh"]
    environment:
      API_URL: "http://backend:8000"
      PORT: 3000
    volumes:
      - ./frontend:/frontend
      - node_modules:/frontend/node_modules
    ports:
      - 3000:3000
    depends_on:
      - backend

volumes:
  node_modules:
